package com.codemavricks.zerohunger;

import java.io.*;

import jakarta.servlet.http.*;
import jakarta.servlet.annotation.*;

/**
 * HelloServlet - Traditional Servlet Example (NOT USED IN API).
 * 
 * <h2>Java EE / Jakarta EE Concepts Demonstrated:</h2>
 * 
 * <h3>1. SERVLET API (LEGACY WEB TIER)</h3>
 * <ul>
 *   <li><b>@WebServlet</b>: Maps servlet to URL path /hello-servlet</li>
 *   <li><b>HttpServlet</b>: Base class for HTTP request handling</li>
 *   <li><b>Lifecycle Methods</b>:</li>
 *   <ul>
 *     <li>init(): Called once when servlet is loaded</li>
 *     <li>doGet(): Handles HTTP GET requests</li>
 *     <li>destroy(): Called when servlet is unloaded</li>
 *   </ul>
 * </ul>
 * 
 * <h3>2. SERVLET VS JAX-RS (COMPARISON)</h3>
 * <ul>
 *   <li><b>Servlet</b> (this file):</li>
 *   <ul>
 *     <li>Lower-level API, manual request/response handling</li>
 *     <li>HTML generation in Java code (mixing concerns)</li>
 *     <li>URL mapping: @WebServlet(value="/hello-servlet")</li>
 *     <li>Used in older Java EE applications</li>
 *   </ul>
 *   <li><b>JAX-RS</b> (DonationResource, etc.):</li>
 *   <ul>
 *     <li>Higher-level REST API framework</li>
 *     <li>Automatic JSON serialization/deserialization</li>
 *     <li>Annotation-based: @Path, @GET, @POST</li>
 *     <li>Modern approach for RESTful services</li>
 *   </ul>
 * </ul>
 * 
 * <h3>3. WHY THIS FILE EXISTS</h3>
 * <ul>
 *   <li>Generated by project template (IDE or archetype)</li>
 *   <li>Not used in actual Zero Hunger API</li>
 *   <li>Can be deleted without affecting functionality</li>
 *   <li>Kept for educational comparison</li>
 * </ul>
 * 
 * <h3>4. N-TIER ARCHITECTURE VIOLATION</h3>
 * <ul>
 *   <li>HTML generation mixed with business logic (message)</li>
 *   <li>No separation of concerns</li>
 *   <li>Contrast with: Resource (web) → Service (business) → Entity (data)</li>
 * </ul>
 * 
 * <h3>Related Book Concepts:</h3>
 * <ul>
 *   <li><b>History</b>: Servlet API is foundation of Java web applications</li>
 *   <li><b>Evolution</b>: Servlets → JSP → JSF → JAX-RS</li>
 *   <li><b>Chapter</b>: Web Tier - Servlet containers</li>
 *   <li><b>Modern</b>: JAX-RS preferred for REST APIs</li>
 * </ul>
 * 
 * <h3>Equivalent JAX-RS Code:</h3>
 * <pre>
 * &#64;Path("/hello")
 * public class HelloResource {
 *     &#64;GET
 *     &#64;Produces(MediaType.TEXT_HTML)
 *     public String hello() {
 *         return "&lt;html&gt;&lt;body&gt;&lt;h1&gt;Hello World!&lt;/h1&gt;&lt;/body&gt;&lt;/html&gt;";
 *     }
 * }
 * </pre>
 * 
 * @author Project Template
 * @version 1.0
 * @deprecated Not used in Zero Hunger API, JAX-RS resources used instead
 */
@Deprecated
@WebServlet(name = "helloServlet", value = "/hello-servlet")
public class HelloServlet extends HttpServlet {
    private String message;

    public void init() {
        message = "Hello World!";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        response.setContentType("text/html");

        // Hello
        PrintWriter out = response.getWriter();
        out.println("<html><body>");
        out.println("<h1>" + message + "</h1>");
        out.println("</body></html>");
    }

    public void destroy() {
    }
}